---
  - name: Update cache
    apt:
      update_cache: yes

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Install Docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present

  - name: Add user to Docker group
    user:
      name: "{{ USER }}"
      groups: docker
      append: yes

  - name: Start syslog
    systemd:
      name: syslog
      state: started
      enabled: yes

  - name: Add syslog to daemon.json
    copy:
      content: '{ "log-driver": "syslog" }'
      dest: /etc/docker/daemon.json
  
  - name: Start the Docker service
    systemd:
      name: docker
      state: restarted
      enabled: yes
  